### ISSUE TITLE
where is "icvl_test_128.h5"?

### ISSUE THREAD

**Issue by HOMGH** [razvancaramalau/al_bhpe#1]
Hi, 
Thanks for sharing the source code. Just trying to run the code and got the error of "No such file or directory" while looking for icvl_test_128.h5.
Could you please advise where I can find this to put in the path?
Thanks.

**Comment by razvancaramalau** [comment]
Hi,

In the description says to e-mail me, and I can provide the pre-processed subsets.
You can also create them yourself from the corresponding websites of the datasets (in that case ICVL Hand dataset).

Thanks
